source 'https://github.com/CocoaPods/Specs.git'

target 'SingleLineInput', :exclusive => true do
  pod "SingleLineInput", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SingleLineInput", :path => "../"
end
